GAME		= Space Quest II
TRACKS		= 80
DISK1		= SpaceQuestII.dsk
DISK1_NAME	= "Space Quest II"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 vol.3 words.tok

include ../sierra-game.mak
