GAME		= King's Quest III
TRACKS		= 80
DISK1		= KingsQuestIII.dsk
DISK1_NAME	= "King's Quest III"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 vol.3 vol.4 vol.5 vol.6 vol.7 vol.8 vol.9 \
		vol.11 vol.12 vol.14 words.tok

include ../sierra-game.mak
