GAME		= Leisure Suit Larry
TRACKS		= 80
DISK1		= LeisureSuitLarry.dsk
DISK1_NAME	= "Leisure Suit Larry"
TOC_INPUT	= tOC.txt
STARTUP		=
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 vol.3 vol.4 words.tok

include ../sierra-game.mak
