* CoCo sound state and CPU-calibrated tables. Included at the original
* engine location to preserve all addresses. State remains in the private
* engine copy; it must not be shared between concurrent processes.

SoundPIA1Ctrl       fcb       0
SoundPIA2Ctrl       fcb       0
SoundEnableReg      fcb       0

NoteFreqTable       fcb       $07,$78
                    fcb       $07,$0C
                    fcb       $06,$A8
                    fcb       $06,$48
                    fcb       $05,$EC
                    fcb       $05,$98
                    fcb       $05,$48
                    fcb       $04,$FC
                    fcb       $04,$B4
                    fcb       $04,$70
                    fcb       $04,$30
                    fcb       $03,$F4
                    fcb       $03,$BC
                    fcb       $03,$86
                    fcb       $03,$54
                    fcb       $03,$24
                    fcb       $02,$F6
                    fcb       $02,$CC
                    fcb       $02,$A4
                    fcb       $02,$7E
                    fcb       $02,$5A
                    fcb       $02,$38
                    fcb       $02,$18
                    fcb       $01,$FA
                    fcb       $01,$DE
                    fcb       $01,$C2
                    fcb       $01,$AA
                    fcb       $01,$92
                    fcb       $01,$7A
                    fcb       $01,$66
                    fcb       $01,$52
                    fcb       $01,$3E
                    fcb       $01,$2C
                    fcb       $01,$1C
                    fcb       $01,$0C
                    fcb       $00,$FC
                    fcb       $00,$EE
                    fcb       $00,$E2
                    fcb       $00,$D4
                    fcb       $00,$C8
                    fcb       $00,$BE
                    fcb       $00,$B2
                    fcb       $00,$A8
                    fcb       $00,$9C
                    fcb       $00,$96
                    fcb       $00,$8E
                    fcb       $00,$86
                    fcb       $00,$7E
                    fcb       $00,$78
                    fcb       $00,$70
                    fcb       $00,$6A
                    fcb       $00,$64
                    fcb       $00,$5E
                    fcb       $00,$5A
                    fcb       $00,$54
                    fcb       $00,$50
                    fcb       $00,$4C
                    fcb       $00,$46
                    fcb       $00,$42
                    fcb       $00,$3E
                    fcb       $00,$3C
                    fcb       $00,$02
                    fcb       $00,$02
                    fcb       $00,$02
                    fcb       $00,$03
                    fcb       $00,$03
                    fcb       $00,$03
                    fcb       $00,$03
                    fcb       $00,$03
                    fcb       $00,$03
                    fcb       $00,$04
                    fcb       $00,$04
                    fcb       $00,$04
                    fcb       $00,$04
                    fcb       $00,$05
                    fcb       $00,$05
                    fcb       $00,$05
                    fcb       $00,$05
                    fcb       $00,$06
                    fcb       $00,$06
                    fcb       $00,$06
                    fcb       $00,$07
                    fcb       $00,$07
                    fcb       $00,$08
                    fcb       $00,$08
                    fcb       $00,$09
                    fcb       $00,$09
                    fcb       $00,$0A
                    fcb       $00,$0A
                    fcb       $00,$0B
                    fcb       $00,$0C
                    fcb       $00,$0C
                    fcb       $00,$0D
                    fcb       $00,$0E
                    fcb       $00,$0E
                    fcb       $00,$0F
                    fcb       $00,$10
                    fcb       $00,$11
                    fcb       $00,$12
                    fcb       $00,$13
                    fcb       $00,$14
                    fcb       $00,$15
                    fcb       $00,$17
                    fcb       $00,$19
                    fcb       $00,$1A
                    fcb       $00,$1B
                    fcb       $00,$1D
                    fcb       $00,$1E
                    fcb       $00,$20
                    fcb       $00,$22
                    fcb       $00,$24
                    fcb       $00,$26
                    fcb       $00,$28
                    fcb       $00,$2B
                    fcb       $00,$2D
                    fcb       $00,$30
                    fcb       $00,$33
                    fcb       $00,$35
                    fcb       $00,$39
                    fcb       $00,$3D
                    fcb       $00,$40
                    fcb       $00,$42
