GAME		= Space Quest I
TRACKS		= 80
DISK1		= SpaceQuestI.dsk
DISK1_NAME	= "Space Quest I"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 words.tok

include ../sierra-game.mak
