GAME		= Gold Rush
TRACKS		= 80
DISK1		= GoldRush_d1_80d.dsk
DISK2		= GoldRush_d2_80d.dsk
DISK3		= GoldRush_d3_80d.dsk
DISK1_NAME	= "Gold Rush Disk 1"
DISK2_NAME	= "Gold Rush Disk 2"
DISK3_NAME	= "Gold Rush Disk 3"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 vol.9 vol.10 vol.11 vol.12 words.tok
SUPPORTFILES2	= object vol.0 vol.3 vol.9 vol.11
SUPPORTFILES3	= object vol.0 vol.4 vol.5 vol.9 vol.11 vol.12

include ../sierra-game.mak
