GAME		= Police Quest I
TRACKS		= 40
DISK1		= PoliceQuestI_d1_40d.dsk
DISK2		= PoliceQuestI_d2_40d.dsk
DISK3		= PoliceQuestI_d3_40d.dsk
DISK1_NAME	= "Police Quest I Disk 1"
DISK2_NAME	= "Police Quest I Disk 2"
DISK3_NAME	= "Police Quest I Disk 3"
TOC_INPUT	= tOC_40d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 vol.1 words.tok
SUPPORTFILES2	= object vol.0 vol.2
SUPPORTFILES3	= object vol.0 vol.3

include ../sierra-game.mak
