GAME		= Space Quest 0
TRACKS		= 80
DISK1		= SpaceQuest0_d1_80d.dsk
DISK2		= SpaceQuest0_d2_80d.dsk
DISK1_NAME	= "Space Quest 0 Disk 1"
DISK2_NAME	= "Space Quest 0 Disk 2"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 words.tok
SUPPORTFILES2	= object vol.0 vol.3

include ../sierra-game.mak
