GAME		= King's Quest II
TRACKS		= 80
DISK1		= KingsQuestII.dsk
DISK1_NAME	= "King's Quest II"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 words.tok

include ../sierra-game.mak
