GAME		= Christmas 1986
TRACKS		= 40
DISK1		= Christmas86.dsk
DISK1_NAME	= "Christmas 1986"
TOC_INPUT	= tOC.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 words.tok

include ../sierra-game.mak
