GAME		= Manhunter II
TRACKS		= 80
DISK1		= ManHunterII_d1_80d.dsk
DISK2		= ManHunterII_d2_80d.dsk
DISK3		= ManHunterII_d3_80d.dsk
DISK1_NAME	= "Manhunter II Disk 1"
DISK2_NAME	= "Manhunter II Disk 2"
DISK3_NAME	= "Manhunter II Disk 3"
TOC_INPUT	= tOC_80d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.9 vol.10 vol.11 words.tok
SUPPORTFILES2	= object vol.0 vol.2 vol.9 vol.10 vol.11
SUPPORTFILES3	= object vol.0 vol.3 vol.9 vol.10 vol.11

include ../sierra-game.mak
