GAME		= King's Quest I
TRACKS		= 40
DISK1		= KingsQuestI.dsk
DISK1_NAME	= "King's Quest I"
TOC_INPUT	= tOC_40d.txt
SUPPORTFILES1	= logDir object picDir sndDir viewDir vol.0 \
		vol.1 vol.2 words.tok

include ../sierra-game.mak
